logging:
  level:
    root: info
server:
  port: 8080
  servlet:
    context-path: /
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      initial-size: 1
      max-active: 20
      min-idle: 1
      stat-view-servlet:
        allow: true
      test-on-borrow: true
    password: qwaszx
    url: jdbc:mysql://123.56.13.13:3306/springboot_demo?useUnicode=true&amp;characterEncoding=utf-8
    username: root
  thymeleaf:
    cache: true